Acme\Bundle\AppBundle\Model\ProductValue:
    type: entity
    table: pim_catalog_product_value
    manyToMany:
        fabrics:
            targetEntity: Acme\Bundle\AppBundle\Entity\Fabric
            cascade:
                - refresh
            joinTable:
                name: acme_catalog_product_value_fabric
                joinColumns:
                    value_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
                inverseJoinColumns:
                    fabric_id:
                        referencedColumnName: id
                        nullable: false
