parameters:
    pim_catalog.event_subscriber.create_attribute_requirement.class: Pim\Bundle\CatalogBundle\EventSubscriber\CreateAttributeRequirementSubscriber
    pim_catalog.event_subscriber.localizable.class:                  Pim\Bundle\CatalogBundle\EventSubscriber\LocalizableSubscriber
    pim_catalog.event_subscriber.scopable.class:                     Pim\Bundle\CatalogBundle\EventSubscriber\ScopableSubscriber
    pim_catalog.event_subscriber.timestampable.class:                Pim\Bundle\CatalogBundle\EventSubscriber\TimestampableSubscriber
    pim_catalog.event_subscriber.outdate_indexed_values.class:       Pim\Bundle\CatalogBundle\EventSubscriber\OutdateIndexedValuesSubscriber
    pim_catalog.event_subscriber.category.check_channels.class:      Pim\Bundle\CatalogBundle\EventSubscriber\Category\CheckChannelsOnDeletionSubscriber
    pim_catalog.event_subscriber.configure_orm_mappings.class:       Akeneo\Bundle\StorageUtilsBundle\EventSubscriber\ConfigureOrmMappingsSubscriber

services:
    # Subscribers
    pim_catalog.event_subscriber.create_attribute_requirement:
        class: %pim_catalog.event_subscriber.create_attribute_requirement.class%
        arguments:
            - '@pim_catalog.factory.attribute_requirement'
        tags:
            - { name: doctrine.event_subscriber }

    pim_catalog.event_subscriber.metric_base_values:
        class: %pim_catalog.event_subscriber.metric_base_values.class%
        arguments:
            - '@akeneo_measure.measure_converter'
            - '@akeneo_measure.manager'
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber, priority: 1 }

    pim_catalog.event_subscriber.localizable:
        class: %pim_catalog.event_subscriber.localizable.class%
        arguments:
            - '@pim_catalog.context.catalog'
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_subscriber.scopable:
        class: %pim_catalog.event_subscriber.scopable.class%
        arguments:
            - '@pim_catalog.context.catalog'
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_subscriber.timestampable:
        class: %pim_catalog.event_subscriber.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_subscriber.outdate_indexed_values:
        class: %pim_catalog.event_subscriber.outdate_indexed_values.class%
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_subscriber.category.check_channels:
        class: %pim_catalog.event_subscriber.category.check_channels.class%
        arguments:
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    pim_catalog.event_subscriber.configure_orm_mappings:
        class: %pim_catalog.event_subscriber.configure_orm_mappings.class%
        arguments:
            -
                - %pim_catalog.entity.product_value.class%
                - %pim_user.entity.role.class%
                - %pim_user.entity.group.class%
                - %pim_user.entity.user.class%
                - %pim_user.entity.user_api.class%
                - %pim_notification.entity.notification.class%
                - %pim_notification.entity.user_notification.class%
                - %pim_versioning.entity.version.class%
                - %akeneo_batch.entity.job_instance.class%
                - %akeneo_batch.entity.job_execution.class%
                - %akeneo_batch.entity.step_execution.class%
                - %akeneo_batch.job.batch_status.class%
                - %pim_catalog.entity.product.class%
                - %pim_catalog.entity.product_value.class%
                - %pim_catalog.entity.association.class%
                - %pim_catalog.entity.completeness.class%
                - %pim_catalog.entity.association_type.class%
                - %pim_catalog.entity.association_type_translation.class%
                - %pim_catalog.entity.category.class%
                - %pim_catalog.entity.category_translation.class%
                - %pim_catalog.entity.group.class%
                - %pim_catalog.entity.group_translation.class%
                - %pim_catalog.entity.group_type.class%
                - %pim_catalog.entity.group_type_translation.class%
                - %pim_catalog.entity.attribute.class%
                - %pim_catalog.entity.attribute_translation.class%
                - %pim_catalog.entity.attribute_group.class%
                - %pim_catalog.entity.attribute_group_translation.class%
                - %pim_catalog.entity.attribute_option.class%
                - %pim_catalog.entity.attribute_option_value.class%
                - %pim_catalog.entity.attribute_requirement.class%
                - %pim_catalog.entity.family.class%
                - %pim_catalog.entity.family_translation.class%
                - %pim_catalog.entity.channel.class%
                - %pim_catalog.entity.currency.class%
                - %pim_catalog.entity.locale.class%
                - %pim_catalog.entity.metric.class%
                - %pim_catalog.entity.product_media.class%
                - %pim_catalog.entity.product_price.class%
                - %pim_catalog.entity.product_template.class%
                - %pim_catalog.entity.available_attributes.class%
                - %pim_comment.entity.comment.class%
                - %pim_enrich.entity.sequential_edit.class%
                - %pim_reference_data.model.abstract_reference_data.class%
                - %pim_base_connector.model.job_configuration.class%
                - %akeneo_batch.entity.field_mapping.class%
                - %akeneo_batch.entity.item_mapping.class%
                - %akeneo_batch.entity.warning.class%
                - %oro_user.group.entity.class%
                - %oro_user.role.entity.class%
                - %oro_user.entity.class%
        tags:
            - { name: doctrine.event_subscriber }
